image: node:10

pipelines:
  branches:
    dev:
      - step:
          name: Next.js Build
          caches:
            - node
          script:
            - yarn install
            - yarn export
      - step:
          name: Deployment to Pages
          deployment: production
          script:
            - echo "Deployment"
