image: node:11-alpine

definitions:
  steps:
    - step: &lint
        name: Lint
        caches:
          - node
        script:
          - npm install
          - npm run lint

pipelines:
  default:
    - step: *lint
  branches:
    master:
      - step: *lint
      - step:
          name: Next.js build
          caches:
            - node
          script:
            - npm install
            - NODE_ENV=production npm run export
